ESG/Models/ESGmodel.cs
namespace ESG.Models
{
    public class ESGmodel
    {
        public int Id { get; set; }
        public string  CompanyNumber { get; set; }
        public string CompanyName { get; set; }
        public string SusESG { get; set; }
        public string MsciESG { get; set; }
        public string FtseESG { get; set; }
        public string IssESG { get; set; }
        public string SapESG { get; set; }
        public string TwCompanyRank { get; set; }
        public string Refi { get; set; }

    }
}

ESG/Models/ErrorViewModel.cs
namespace ESG.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ESG/Controllers/ESGController.cs
using ESG.ESGDbContext;
using ESG.ESGDbContext.ESGaction;
using ESG.Models;
using Microsoft.AspNetCore.Mvc;

namespace ESG.Controllers
{
    public class ESGController : Controller
    {
        private readonly IESGaction _dbcontext;
        public ESGController(IESGaction dbcontext)
        {
            _dbcontext = dbcontext;
        }
        public IActionResult Index()
        {           
            return View();
        }

        public IActionResult Company(int id)
        {
            var data = _dbcontext.GetFirstOrDefault(u=>u.Id == id);
            return View(data);
        }

        public IActionResult AllContent()
        {
            return View();
        }

        #region API CALLS
        public IActionResult GetAll()
        {
            var list = _dbcontext.GetAll();
            //把資料回傳成Json格式
            return Json(new { data = list });
        }
        public IActionResult GetAllData()
        {
            var list = _dbcontext.GetAll();
            //把資料回傳成Json格式
            return Json(list);
        }
        #endregion
    }


}

ESG/Controllers/HomeController.cs
using ESG.ESGDbContext.ESGaction;
using ESG.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ESG.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IESGaction _dbcontext;
        public HomeController(ILogger<HomeController> logger, IESGaction dbcontext)
        {
            _logger = logger;
            _dbcontext = dbcontext;

        }

        public IActionResult Index()
        {                        
            return View();
        }

        public IActionResult searchItem(string? search) {
            var data = _dbcontext.GetAll();
            var searchRes = data.Where(u => u.CompanyNumber.Contains(search) || u.CompanyName.Contains(search));
            if (searchRes !=null || searchRes.Any())
                return PartialView("_searchPartial", searchRes);
            return View();
        }
                

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ESG/Views/ESG/AllContent.cshtml
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-warning">ESG 總表</h2>
        </div>
    </div>
<div class="container p-3">
<table id="tbltable" class="table table-bordered table-striped tableFont" style="width:100%">
	<thead>
		<tr>
			<th>Id</th>
			<th>CompanyNumber</th>
			<th>CompanyName</th>
			<th>SusESG</th>
			<th>MsciESG</th>
			<th>FtseESG</th>
			<th>IssESG</th>
			<th>SapESG</th>
			<th>TwCompanyRank</th>
			<th>Refi</th>
		</tr>
	</thead>
	<tbody>
        
    </tbody>
</table>
</div>
@section Scripts{
    <script src="~/js/ESGtable.js"></script>
}

ESG/Views/ESG/Company.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ESGmodel

<div class="min-vh-50 pt-5" style="background-color:#222324">
    <h1>留白處</h1>
</div>

<div class="container pt-5 min-vh-100" style="background-color:#0f1e2b">
    <div class="p-4 border border-5">
        <div class="row">
            <div class="col-3 list-group vh-100">
                <a href="#" class="list-group-item list-group-item-action active" aria-current="true">
                The current link item
                </a>
                <a href="#" class="list-group-item list-group-item-action">A second link item</a>
                <a href="#" class="list-group-item list-group-item-action">A third link item</a>
                <a href="#" class="list-group-item list-group-item-action">A fourth link item</a>
                <a class="list-group-item list-group-item-action disabled">A disabled link item</a>
                <a href="#" class="list-group-item list-group-item-action">A second link item</a>
                <a href="#" class="list-group-item list-group-item-action">A third link item</a>
                <a href="#" class="list-group-item list-group-item-action">A fourth link item</a>
                <a class="list-group-item list-group-item-action disabled">A disabled link item</a>
                <a href="#" class="list-group-item list-group-item-action">A second link item</a>
                <a href="#" class="list-group-item list-group-item-action">A third link item</a>
                <a href="#" class="list-group-item list-group-item-action">A fourth link item</a>
                <a class="list-group-item list-group-item-action disabled">A disabled link item</a>
            </div>
            <div class="col-9">                
                <h1>@Model.CompanyNumber</h1>
                <h1>@Model.CompanyName</h1>
                <table class="table">
                    <thead>
                        <tr>
                            <th>SusEsg</th>
                            <th>MsciEsg</th>
                            <th>FtseEsg</th>
                            <th>IssESG</th>
                            <th>SapEsg</th>
                            <th>TwCompanyRank</th>
                            <th>Refi</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Model.SusESG</td>
                            <td>@Model.MsciESG</td>
                            <td>@Model.FtseESG</td>
                            <td>@Model.IssESG</td>
                            <td>@Model.SapESG</td>
                            <td>@Model.TwCompanyRank</td>
                            <td>@Model.Refi</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
</div>

ESG/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
    .h1{
        font-size:100px;
    }
</style>
<div class="backgroundImg" style="background-image:url('../img/background.jpg')">
    <div class="color-overlay d-flex justify-content-center align-items-start">
        <div class="container pt-5">
            <div class="row">
                <h1 class="pt-5">搜尋</h1>
                <div class="col-12">
                    <input id="search" class="form-control" placeholder="123" />
                </div>
                <div class="col-12">
                    <div class="list-group" id="show-list">
                        @*查詢結果*@
                    </div>
                </div>
            
            </div>
        </div>  
    </div>
</div>


@section Scripts{

    <script>
        $(document).ready(function () {
        // 當 Select 的值改變時，載入對應的部分視圖內容
            $("#search").keyup(function () {
                var search = $("#search").val();
                if(search!=''){
                    $.ajax({
                        type: 'Post',
                        url: "/Home/searchItem?search=" + search, // 請自行替換成你的部分視圖控制器的路徑
                        success: function (result) {
                            console.log(search);
                            $('#show-list').html(result);
                        }
                    });
                }
                else{
                    $('#show-list').html('');
                }
            });
        });

    </script>
}

ESG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ESG</title>
    <link rel="stylesheet" href="~/css/bootwatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/DataTable.css" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ESG</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="mt-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted ">
        <div class="container">
            &copy; 2023 - ESG - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ESG/Views/Shared/_searchPartial.cshtml
@model IEnumerable<ESGmodel>



@if(Model.Count() >0){
	@foreach (var item in Model)
	{
		<a asp-area="" asp-controller="ESG" asp-action="Company" asp-route-id="@item.Id" class="list-group-item list-group-item-action  border-1">
			@item.CompanyNumber @item.CompanyName
		</a>
	}
}
else
{
	<a herf ='#' class="list-group-item list-group-item-action  border-1">
		找不到ㄟ
	</a>
}